using System;
using System.Windows;

namespace InteractiveWorldMap.Models
{
    /// <summary>
    /// Represents a manually positioned marker in a saved layout
    /// </summary>
    public class ManualLayoutMarker
    {
        public string LocationName { get; set; } = string.Empty;
        public Point OriginalPosition { get; set; }
        public Point ExtendedPosition { get; set; }
        public double Angle { get; set; }
        public double LineLength { get; set; }

        /// <summary>
        /// Source-image X coordinate of the extended position (optional).
        /// When present the extended position is re-projected from source space using the
        /// current viewport at load time, making saved layouts viewport-size-independent.
        /// Seeds generated by the script populate this; user-saved layouts do not yet.
        /// </summary>
        public double? SourceExtendedX { get; set; }

        /// <summary>
        /// Source-image Y coordinate of the extended position (optional).
        /// See <see cref="SourceExtendedX"/>.
        /// </summary>
        public double? SourceExtendedY { get; set; }

        /// <summary>
        /// Shaft pair id from <see cref="CompositePinRenderPlan.PairId"/> at save time.
        /// Null → scorer chooses the best-fit pair on replay.
        /// </summary>
        public string? PairId { get; set; }

        /// <summary>
        /// Head asset path from <see cref="CompositePinRenderPlan.HeadSourcePath"/> at save time.
        /// Null → location-hash fallback on replay.
        /// </summary>
        public string? HeadSourcePath { get; set; }

        public ManualLayoutMarker() { }

        public ManualLayoutMarker(string locationName, Point originalPos, Point extendedPos, double angle, double length)
        {
            LocationName = locationName;
            OriginalPosition = originalPos;
            ExtendedPosition = extendedPos;
            Angle = angle;
            LineLength = length;
        }

        /// <summary>
        /// Create from a RadialExtension
        /// </summary>
        public static ManualLayoutMarker FromRadialExtension(RadialExtension extension)
        {
            return new ManualLayoutMarker(
                extension.Location.Name,
                extension.OriginalPosition,
                extension.ExtendedPosition,
                extension.Angle,
                CalculateLength(extension.OriginalPosition, extension.ExtendedPosition)
            );
        }

        private static double CalculateLength(Point p1, Point p2)
        {
            double dx = p2.X - p1.X;
            double dy = p2.Y - p1.Y;
            return Math.Sqrt(dx * dx + dy * dy);
        }
    }
}
